### PR TITLE
Reading token from external file

### LINKED ISSUE #12: Read Token from external sources
Seeing that a lot of people are forgetting to remove their access token from the code before pushing, I would recommend to add a way to read the Token from an external config file or environment variable, and then gitignore that config file

### PR DESCRIPTION
**Pull request by hecoding**
Made to close #12 building on top of @Kuronogard comment https://github.com/LibreLabUCM/teleg-api-bot/issues/12#issuecomment-120135155.

### CODE REVIEW

**Comment by ergl** [comment]
I was thinking about this issue the other day, and I actually changed my mind in the sense that I don't think the library should deal with getting tokens from files, etc - the user should deal with that, and pass the token to the library as we do right now.

EDIT:  If we end up implementing this, I think the `Telegbot` class should at least receive the token file as an argument

**Comment by ergl** [comment]
With that being said, maybe we could implement some error handling on `connect` so that we know if the token is valid. `Telegbot#__api_request` should return some kind of error on `401`/`403` or other unauth response and present that to the user

**Comment by dpriver** [comment]
Agree.

**Comment by hecoding** [comment]
Ok I forgot it'll be used as a library when coding :sweat_smile:.
So yes, user dealing with the token is much more sensible in my opinion.

About the error handling, the API provides a description of the error that we could use. I'll open a new pull request for that.

**Pull request closed without merging**
